data:
  initial_file: train.csv
model_type: "image"
image:
 image_size: (512,512)
 unfreeze: "234"
 pre_trained_name: "EfficientNetB1"
text:
  max_length: "270"
  pre_trained_name: "bert-base-uncased"
scheduler: "one_cycle"
#234