data:
  initial_file: train.csv
model_type: "text"
image:
 image_size: (256,256)
 unfreeze: "0"
 pre_trained_name: "EfficientNetB1"
text:
  max_length: "270"
  pre_trained_name: "bert-base-uncased"
scheduler: "None"
